/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedDashboardChildIdRouteImport } from './routes/_authenticated/dashboard.$childId'
import { Route as AuthenticatedCoachChildIdRouteImport } from './routes/_authenticated/coach.$childId'
import { Route as AuthenticatedBoardChildIdRouteImport } from './routes/_authenticated/board.$childId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardChildIdRoute =
  AuthenticatedDashboardChildIdRouteImport.update({
    id: '/dashboard/$childId',
    path: '/dashboard/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachChildIdRoute =
  AuthenticatedCoachChildIdRouteImport.update({
    id: '/coach/$childId',
    path: '/coach/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardChildIdRoute =
  AuthenticatedBoardChildIdRouteImport.update({
    id: '/board/$childId',
    path: '/board/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/board/$childId': typeof AuthenticatedBoardChildIdRoute
  '/coach/$childId': typeof AuthenticatedCoachChildIdRoute
  '/dashboard/$childId': typeof AuthenticatedDashboardChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/board/$childId': typeof AuthenticatedBoardChildIdRoute
  '/coach/$childId': typeof AuthenticatedCoachChildIdRoute
  '/dashboard/$childId': typeof AuthenticatedDashboardChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/board/$childId': typeof AuthenticatedBoardChildIdRoute
  '/_authenticated/coach/$childId': typeof AuthenticatedCoachChildIdRoute
  '/_authenticated/dashboard/$childId': typeof AuthenticatedDashboardChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/board/$childId'
    | '/coach/$childId'
    | '/dashboard/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/board/$childId'
    | '/coach/$childId'
    | '/dashboard/$childId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/board/$childId'
    | '/_authenticated/coach/$childId'
    | '/_authenticated/dashboard/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/$childId': {
      id: '/_authenticated/dashboard/$childId'
      path: '/dashboard/$childId'
      fullPath: '/dashboard/$childId'
      preLoaderRoute: typeof AuthenticatedDashboardChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/$childId': {
      id: '/_authenticated/coach/$childId'
      path: '/coach/$childId'
      fullPath: '/coach/$childId'
      preLoaderRoute: typeof AuthenticatedCoachChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board/$childId': {
      id: '/_authenticated/board/$childId'
      path: '/board/$childId'
      fullPath: '/board/$childId'
      preLoaderRoute: typeof AuthenticatedBoardChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedBoardChildIdRoute: typeof AuthenticatedBoardChildIdRoute
  AuthenticatedCoachChildIdRoute: typeof AuthenticatedCoachChildIdRoute
  AuthenticatedDashboardChildIdRoute: typeof AuthenticatedDashboardChildIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedBoardChildIdRoute: AuthenticatedBoardChildIdRoute,
  AuthenticatedCoachChildIdRoute: AuthenticatedCoachChildIdRoute,
  AuthenticatedDashboardChildIdRoute: AuthenticatedDashboardChildIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
