
-- Helper: seed categories + cards for one child
CREATE OR REPLACE FUNCTION public.seed_categories_for_child(p_child_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.categories (child_id, name, icon, color, sort_order) VALUES
    (p_child_id, 'Giao tiếp Cơ bản', '💬', '#95A5FF', 1),
    (p_child_id, 'Người thân', '👨‍👩‍👧', '#FCBAD3', 2),
    (p_child_id, 'Hành động', '🏃', '#FFE66D', 3),
    (p_child_id, 'Đồ ăn & Thức uống', '🍎', '#FF6B6B', 4),
    (p_child_id, 'Đồ vật & Đồ chơi', '🧸', '#AA96DA', 5),
    (p_child_id, 'Cảm xúc & Cơ thể', '😊', '#F38181', 6),
    (p_child_id, 'Thời gian', '🕐', '#74B9FF', 7),
    (p_child_id, 'Số', '🔢', '#FDCB6E', 8),
    (p_child_id, 'Động vật', '🐶', '#55EFC4', 9),
    (p_child_id, 'Thể thao', '⚽', '#FF7675', 10),
    (p_child_id, 'Cây cối', '🌳', '#6AB04C', 11),
    (p_child_id, 'Nội thất', '🛋️', '#B59E84', 12),
    (p_child_id, 'Công nghệ', '💻', '#636E72', 13),
    (p_child_id, 'Phương tiện', '🚗', '#0984E3', 14),
    (p_child_id, 'Quần áo', '👕', '#E17055', 15),
    (p_child_id, 'Vệ sinh', '🧼', '#81ECEC', 16),
    (p_child_id, 'Nơi chốn', '🏠', '#A8E6CF', 17),
    (p_child_id, 'Cụm chức năng', '✨', '#A29BFE', 18);

  INSERT INTO public.cards (child_id, category_id, label, emoji, part_of_speech, context_tags)
  SELECT p_child_id, c.id, v.label, v.emoji, v.pos::part_of_speech, v.tags
  FROM public.categories c
  JOIN (VALUES
    ('Giao tiếp Cơ bản','Xin chào','👋','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Tạm biệt','👋','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Cảm ơn','🙏','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Xin lỗi','😔','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Có','✅','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Không','❌','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Con muốn','🙋','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Con không muốn','🙅','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Giúp con','🆘','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Làm ơn','🙏','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Xong rồi','✔️','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Thêm nữa','➕','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Dừng lại','✋','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Đợi','⏳','phrase',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Con','🧒','pronoun',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Bạn','👦','pronoun',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Đây','👉','pronoun',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Kia','👈','pronoun',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Cái này','🫵','pronoun',ARRAY[]::text[]),
    ('Giao tiếp Cơ bản','Cái gì','❓','phrase',ARRAY[]::text[]),

    ('Người thân','Mẹ','👩','noun',ARRAY[]::text[]),
    ('Người thân','Bố','👨','noun',ARRAY[]::text[]),
    ('Người thân','Bà','👵','noun',ARRAY[]::text[]),
    ('Người thân','Ông','👴','noun',ARRAY[]::text[]),
    ('Người thân','Anh','👦','noun',ARRAY[]::text[]),
    ('Người thân','Chị','👧','noun',ARRAY[]::text[]),
    ('Người thân','Em','🧒','noun',ARRAY[]::text[]),
    ('Người thân','Cô','👩‍🏫','noun',ARRAY[]::text[]),
    ('Người thân','Chú','👨‍🦱','noun',ARRAY[]::text[]),
    ('Người thân','Dì','👩‍🦰','noun',ARRAY[]::text[]),
    ('Người thân','Cậu','👨‍🦰','noun',ARRAY[]::text[]),
    ('Người thân','Bác','👨‍🦳','noun',ARRAY[]::text[]),
    ('Người thân','Bạn thân','👫','noun',ARRAY[]::text[]),
    ('Người thân','Thầy','👨‍🏫','noun',ARRAY[]::text[]),
    ('Người thân','Cô giáo','👩‍🏫','noun',ARRAY[]::text[]),
    ('Người thân','Bác sĩ','👨‍⚕️','noun',ARRAY[]::text[]),
    ('Người thân','Em bé','👶','noun',ARRAY[]::text[]),
    ('Người thân','Gia đình','👨‍👩‍👧','noun',ARRAY[]::text[]),
    ('Người thân','Hàng xóm','🏘️','noun',ARRAY[]::text[]),
    ('Người thân','Người lạ','🚶','noun',ARRAY[]::text[]),

    ('Hành động','Ăn','🍽️','verb',ARRAY['meal']),
    ('Hành động','Uống','🥤','verb',ARRAY[]::text[]),
    ('Hành động','Ngủ','😴','verb',ARRAY['evening']),
    ('Hành động','Chơi','🎮','verb',ARRAY[]::text[]),
    ('Hành động','Tắm','🛁','verb',ARRAY['evening']),
    ('Hành động','Đi','🚶','verb',ARRAY[]::text[]),
    ('Hành động','Chạy','🏃','verb',ARRAY[]::text[]),
    ('Hành động','Nhảy','🤸','verb',ARRAY[]::text[]),
    ('Hành động','Ngồi','🪑','verb',ARRAY[]::text[]),
    ('Hành động','Đứng','🧍','verb',ARRAY[]::text[]),
    ('Hành động','Nằm','🛌','verb',ARRAY[]::text[]),
    ('Hành động','Đọc','📖','verb',ARRAY[]::text[]),
    ('Hành động','Viết','✍️','verb',ARRAY[]::text[]),
    ('Hành động','Vẽ','🎨','verb',ARRAY[]::text[]),
    ('Hành động','Hát','🎤','verb',ARRAY[]::text[]),
    ('Hành động','Nghe','👂','verb',ARRAY[]::text[]),
    ('Hành động','Nhìn','👀','verb',ARRAY[]::text[]),
    ('Hành động','Ôm','🤗','verb',ARRAY[]::text[]),
    ('Hành động','Hôn','😘','verb',ARRAY[]::text[]),
    ('Hành động','Cười','😄','verb',ARRAY[]::text[]),

    ('Đồ ăn & Thức uống','Cơm','🍚','noun',ARRAY['meal']),
    ('Đồ ăn & Thức uống','Phở','🍜','noun',ARRAY['meal']),
    ('Đồ ăn & Thức uống','Bánh mì','🥖','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Cháo','🥣','noun',ARRAY['morning']),
    ('Đồ ăn & Thức uống','Thịt','🍖','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Cá','🐟','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Trứng','🥚','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Rau','🥬','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Táo','🍎','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Chuối','🍌','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Cam','🍊','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Nho','🍇','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Bánh kẹo','🍬','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Kem','🍦','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Sữa','🥛','noun',ARRAY['morning']),
    ('Đồ ăn & Thức uống','Nước','💧','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Nước cam','🧃','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Trà','🍵','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Cà phê','☕','noun',ARRAY[]::text[]),
    ('Đồ ăn & Thức uống','Sinh tố','🥤','noun',ARRAY[]::text[]),

    ('Đồ vật & Đồ chơi','Gấu bông','🧸','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Búp bê','🪆','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Xe ô tô','🚗','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Bóng','⚽','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Khối xếp hình','🧩','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Lego','🧱','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Sách','📕','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Bút','✏️','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Giấy','📄','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Màu vẽ','🖍️','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Bóng bay','🎈','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Đàn','🎹','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Trống','🥁','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Diều','🪁','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Robot','🤖','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Đồng hồ','⌚','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Chìa khoá','🔑','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Túi','👜','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Cặp sách','🎒','noun',ARRAY[]::text[]),
    ('Đồ vật & Đồ chơi','Ô','☂️','noun',ARRAY[]::text[]),

    ('Cảm xúc & Cơ thể','Vui','😄','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Buồn','😢','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Giận','😠','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Sợ','😨','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Mệt','😪','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Đau','🤕','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Đói','🍽️','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Khát','💧','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Nóng','🥵','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Lạnh','🥶','adjective',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Đầu','🧠','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Mắt','👁️','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Mũi','👃','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Miệng','👄','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Tai','👂','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Tay','✋','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Chân','🦵','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Bụng','🤰','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Răng','🦷','noun',ARRAY[]::text[]),
    ('Cảm xúc & Cơ thể','Tóc','💇','noun',ARRAY[]::text[]),

    ('Thời gian','Sáng','🌅','noun',ARRAY['morning']),
    ('Thời gian','Trưa','☀️','noun',ARRAY[]::text[]),
    ('Thời gian','Chiều','🌇','noun',ARRAY[]::text[]),
    ('Thời gian','Tối','🌆','noun',ARRAY['evening']),
    ('Thời gian','Đêm','🌙','noun',ARRAY['evening']),
    ('Thời gian','Hôm nay','📅','noun',ARRAY[]::text[]),
    ('Thời gian','Hôm qua','📆','noun',ARRAY[]::text[]),
    ('Thời gian','Ngày mai','🗓️','noun',ARRAY[]::text[]),
    ('Thời gian','Bây giờ','⏰','noun',ARRAY[]::text[]),
    ('Thời gian','Lát nữa','⏳','noun',ARRAY[]::text[]),
    ('Thời gian','Thứ Hai','1️⃣','noun',ARRAY[]::text[]),
    ('Thời gian','Thứ Ba','2️⃣','noun',ARRAY[]::text[]),
    ('Thời gian','Thứ Tư','3️⃣','noun',ARRAY[]::text[]),
    ('Thời gian','Thứ Năm','4️⃣','noun',ARRAY[]::text[]),
    ('Thời gian','Thứ Sáu','5️⃣','noun',ARRAY[]::text[]),
    ('Thời gian','Thứ Bảy','6️⃣','noun',ARRAY[]::text[]),
    ('Thời gian','Chủ Nhật','7️⃣','noun',ARRAY[]::text[]),
    ('Thời gian','Tuần','📅','noun',ARRAY[]::text[]),
    ('Thời gian','Tháng','🗓️','noun',ARRAY[]::text[]),
    ('Thời gian','Năm','🎊','noun',ARRAY[]::text[]),

    ('Số','Một','1️⃣','noun',ARRAY[]::text[]),
    ('Số','Hai','2️⃣','noun',ARRAY[]::text[]),
    ('Số','Ba','3️⃣','noun',ARRAY[]::text[]),
    ('Số','Bốn','4️⃣','noun',ARRAY[]::text[]),
    ('Số','Năm','5️⃣','noun',ARRAY[]::text[]),
    ('Số','Sáu','6️⃣','noun',ARRAY[]::text[]),
    ('Số','Bảy','7️⃣','noun',ARRAY[]::text[]),
    ('Số','Tám','8️⃣','noun',ARRAY[]::text[]),
    ('Số','Chín','9️⃣','noun',ARRAY[]::text[]),
    ('Số','Mười','🔟','noun',ARRAY[]::text[]),
    ('Số','Mười một','1️⃣','noun',ARRAY[]::text[]),
    ('Số','Mười hai','1️⃣','noun',ARRAY[]::text[]),
    ('Số','Hai mươi','2️⃣','noun',ARRAY[]::text[]),
    ('Số','Năm mươi','5️⃣','noun',ARRAY[]::text[]),
    ('Số','Một trăm','💯','noun',ARRAY[]::text[]),
    ('Số','Không','0️⃣','noun',ARRAY[]::text[]),
    ('Số','Nhiều','➕','adjective',ARRAY[]::text[]),
    ('Số','Ít','➖','adjective',ARRAY[]::text[]),
    ('Số','Hết','🚫','adjective',ARRAY[]::text[]),
    ('Số','Nửa','½','adjective',ARRAY[]::text[]),

    ('Động vật','Chó','🐶','noun',ARRAY[]::text[]),
    ('Động vật','Mèo','🐱','noun',ARRAY[]::text[]),
    ('Động vật','Gà','🐔','noun',ARRAY[]::text[]),
    ('Động vật','Vịt','🦆','noun',ARRAY[]::text[]),
    ('Động vật','Bò','🐄','noun',ARRAY[]::text[]),
    ('Động vật','Lợn','🐷','noun',ARRAY[]::text[]),
    ('Động vật','Ngựa','🐴','noun',ARRAY[]::text[]),
    ('Động vật','Thỏ','🐰','noun',ARRAY[]::text[]),
    ('Động vật','Chim','🐦','noun',ARRAY[]::text[]),
    ('Động vật','Cá','🐟','noun',ARRAY[]::text[]),
    ('Động vật','Voi','🐘','noun',ARRAY[]::text[]),
    ('Động vật','Hổ','🐯','noun',ARRAY[]::text[]),
    ('Động vật','Sư tử','🦁','noun',ARRAY[]::text[]),
    ('Động vật','Khỉ','🐒','noun',ARRAY[]::text[]),
    ('Động vật','Gấu','🐻','noun',ARRAY[]::text[]),
    ('Động vật','Hươu cao cổ','🦒','noun',ARRAY[]::text[]),
    ('Động vật','Cá sấu','🐊','noun',ARRAY[]::text[]),
    ('Động vật','Rắn','🐍','noun',ARRAY[]::text[]),
    ('Động vật','Ếch','🐸','noun',ARRAY[]::text[]),
    ('Động vật','Bướm','🦋','noun',ARRAY[]::text[]),

    ('Thể thao','Đá bóng','⚽','verb',ARRAY[]::text[]),
    ('Thể thao','Bóng rổ','🏀','noun',ARRAY[]::text[]),
    ('Thể thao','Bóng chuyền','🏐','noun',ARRAY[]::text[]),
    ('Thể thao','Cầu lông','🏸','noun',ARRAY[]::text[]),
    ('Thể thao','Tennis','🎾','noun',ARRAY[]::text[]),
    ('Thể thao','Bơi','🏊','verb',ARRAY[]::text[]),
    ('Thể thao','Chạy bộ','🏃','verb',ARRAY[]::text[]),
    ('Thể thao','Đạp xe','🚴','verb',ARRAY[]::text[]),
    ('Thể thao','Yoga','🧘','noun',ARRAY[]::text[]),
    ('Thể thao','Võ','🥋','noun',ARRAY[]::text[]),
    ('Thể thao','Trượt patin','⛸️','verb',ARRAY[]::text[]),
    ('Thể thao','Bóng bàn','🏓','noun',ARRAY[]::text[]),
    ('Thể thao','Bowling','🎳','noun',ARRAY[]::text[]),
    ('Thể thao','Golf','⛳','noun',ARRAY[]::text[]),
    ('Thể thao','Leo núi','🧗','verb',ARRAY[]::text[]),
    ('Thể thao','Trượt tuyết','🎿','verb',ARRAY[]::text[]),
    ('Thể thao','Bóng bầu dục','🏉','noun',ARRAY[]::text[]),
    ('Thể thao','Cờ vua','♟️','noun',ARRAY[]::text[]),
    ('Thể thao','Huy chương','🏅','noun',ARRAY[]::text[]),
    ('Thể thao','Cúp','🏆','noun',ARRAY[]::text[]),

    ('Cây cối','Cây','🌳','noun',ARRAY[]::text[]),
    ('Cây cối','Hoa','🌸','noun',ARRAY[]::text[]),
    ('Cây cối','Lá','🍃','noun',ARRAY[]::text[]),
    ('Cây cối','Cỏ','🌱','noun',ARRAY[]::text[]),
    ('Cây cối','Hoa hồng','🌹','noun',ARRAY[]::text[]),
    ('Cây cối','Hoa hướng dương','🌻','noun',ARRAY[]::text[]),
    ('Cây cối','Hoa cúc','🌼','noun',ARRAY[]::text[]),
    ('Cây cối','Hoa sen','🪷','noun',ARRAY[]::text[]),
    ('Cây cối','Xương rồng','🌵','noun',ARRAY[]::text[]),
    ('Cây cối','Cây dừa','🌴','noun',ARRAY[]::text[]),
    ('Cây cối','Cây thông','🌲','noun',ARRAY[]::text[]),
    ('Cây cối','Lúa','🌾','noun',ARRAY[]::text[]),
    ('Cây cối','Nấm','🍄','noun',ARRAY[]::text[]),
    ('Cây cối','Hạt giống','🌰','noun',ARRAY[]::text[]),
    ('Cây cối','Quả','🍒','noun',ARRAY[]::text[]),
    ('Cây cối','Rễ','🌿','noun',ARRAY[]::text[]),
    ('Cây cối','Cành','🪵','noun',ARRAY[]::text[]),
    ('Cây cối','Vườn','🏡','noun',ARRAY[]::text[]),
    ('Cây cối','Rừng','🌲','noun',ARRAY[]::text[]),
    ('Cây cối','Công viên','🏞️','noun',ARRAY[]::text[]),

    ('Nội thất','Giường','🛏️','noun',ARRAY[]::text[]),
    ('Nội thất','Ghế','🪑','noun',ARRAY[]::text[]),
    ('Nội thất','Bàn','🪟','noun',ARRAY[]::text[]),
    ('Nội thất','Sofa','🛋️','noun',ARRAY[]::text[]),
    ('Nội thất','Tủ','🚪','noun',ARRAY[]::text[]),
    ('Nội thất','Kệ sách','📚','noun',ARRAY[]::text[]),
    ('Nội thất','Đèn','💡','noun',ARRAY[]::text[]),
    ('Nội thất','Gương','🪞','noun',ARRAY[]::text[]),
    ('Nội thất','Thảm','🧶','noun',ARRAY[]::text[]),
    ('Nội thất','Rèm cửa','🪟','noun',ARRAY[]::text[]),
    ('Nội thất','Quạt','🌀','noun',ARRAY[]::text[]),
    ('Nội thất','Điều hoà','❄️','noun',ARRAY[]::text[]),
    ('Nội thất','Tủ lạnh','🧊','noun',ARRAY[]::text[]),
    ('Nội thất','Bếp','🍳','noun',ARRAY[]::text[]),
    ('Nội thất','Lò vi sóng','🍱','noun',ARRAY[]::text[]),
    ('Nội thất','Máy giặt','🫧','noun',ARRAY[]::text[]),
    ('Nội thất','Tivi','📺','noun',ARRAY[]::text[]),
    ('Nội thất','Chăn','🛌','noun',ARRAY[]::text[]),
    ('Nội thất','Gối','🛌','noun',ARRAY[]::text[]),
    ('Nội thất','Cửa','🚪','noun',ARRAY[]::text[]),

    ('Công nghệ','Điện thoại','📱','noun',ARRAY[]::text[]),
    ('Công nghệ','Máy tính','💻','noun',ARRAY[]::text[]),
    ('Công nghệ','Máy tính bảng','📱','noun',ARRAY[]::text[]),
    ('Công nghệ','Tivi','📺','noun',ARRAY[]::text[]),
    ('Công nghệ','Camera','📷','noun',ARRAY[]::text[]),
    ('Công nghệ','Tai nghe','🎧','noun',ARRAY[]::text[]),
    ('Công nghệ','Loa','🔊','noun',ARRAY[]::text[]),
    ('Công nghệ','Chuột','🖱️','noun',ARRAY[]::text[]),
    ('Công nghệ','Bàn phím','⌨️','noun',ARRAY[]::text[]),
    ('Công nghệ','Màn hình','🖥️','noun',ARRAY[]::text[]),
    ('Công nghệ','Máy in','🖨️','noun',ARRAY[]::text[]),
    ('Công nghệ','Wifi','📶','noun',ARRAY[]::text[]),
    ('Công nghệ','Sạc pin','🔌','noun',ARRAY[]::text[]),
    ('Công nghệ','Pin','🔋','noun',ARRAY[]::text[]),
    ('Công nghệ','Robot','🤖','noun',ARRAY[]::text[]),
    ('Công nghệ','Đồng hồ thông minh','⌚','noun',ARRAY[]::text[]),
    ('Công nghệ','Trò chơi điện tử','🎮','noun',ARRAY[]::text[]),
    ('Công nghệ','Ứng dụng','📲','noun',ARRAY[]::text[]),
    ('Công nghệ','Mạng','🌐','noun',ARRAY[]::text[]),
    ('Công nghệ','Email','📧','noun',ARRAY[]::text[]),

    ('Phương tiện','Ô tô','🚗','noun',ARRAY[]::text[]),
    ('Phương tiện','Xe máy','🏍️','noun',ARRAY[]::text[]),
    ('Phương tiện','Xe đạp','🚲','noun',ARRAY[]::text[]),
    ('Phương tiện','Xe buýt','🚌','noun',ARRAY[]::text[]),
    ('Phương tiện','Tàu hoả','🚆','noun',ARRAY[]::text[]),
    ('Phương tiện','Máy bay','✈️','noun',ARRAY[]::text[]),
    ('Phương tiện','Tàu thuỷ','🚢','noun',ARRAY[]::text[]),
    ('Phương tiện','Thuyền','⛵','noun',ARRAY[]::text[]),
    ('Phương tiện','Trực thăng','🚁','noun',ARRAY[]::text[]),
    ('Phương tiện','Tên lửa','🚀','noun',ARRAY[]::text[]),
    ('Phương tiện','Taxi','🚕','noun',ARRAY[]::text[]),
    ('Phương tiện','Xe cứu thương','🚑','noun',ARRAY[]::text[]),
    ('Phương tiện','Xe cứu hoả','🚒','noun',ARRAY[]::text[]),
    ('Phương tiện','Xe cảnh sát','🚓','noun',ARRAY[]::text[]),
    ('Phương tiện','Xe tải','🚚','noun',ARRAY[]::text[]),
    ('Phương tiện','Tàu điện','🚇','noun',ARRAY[]::text[]),
    ('Phương tiện','Cáp treo','🚠','noun',ARRAY[]::text[]),
    ('Phương tiện','Xích lô','🛺','noun',ARRAY[]::text[]),
    ('Phương tiện','Ván trượt','🛹','noun',ARRAY[]::text[]),
    ('Phương tiện','Patin','⛸️','noun',ARRAY[]::text[]),

    ('Quần áo','Áo','👕','noun',ARRAY[]::text[]),
    ('Quần áo','Áo thun','👕','noun',ARRAY[]::text[]),
    ('Quần áo','Áo sơ mi','👔','noun',ARRAY[]::text[]),
    ('Quần áo','Áo khoác','🧥','noun',ARRAY[]::text[]),
    ('Quần áo','Quần dài','👖','noun',ARRAY[]::text[]),
    ('Quần áo','Quần đùi','🩳','noun',ARRAY[]::text[]),
    ('Quần áo','Váy','👗','noun',ARRAY[]::text[]),
    ('Quần áo','Đầm','👘','noun',ARRAY[]::text[]),
    ('Quần áo','Mũ','🧢','noun',ARRAY[]::text[]),
    ('Quần áo','Nón','👒','noun',ARRAY[]::text[]),
    ('Quần áo','Giày','👟','noun',ARRAY[]::text[]),
    ('Quần áo','Dép','🩴','noun',ARRAY[]::text[]),
    ('Quần áo','Tất','🧦','noun',ARRAY[]::text[]),
    ('Quần áo','Găng tay','🧤','noun',ARRAY[]::text[]),
    ('Quần áo','Khăn quàng','🧣','noun',ARRAY[]::text[]),
    ('Quần áo','Kính','👓','noun',ARRAY[]::text[]),
    ('Quần áo','Đồng hồ','⌚','noun',ARRAY[]::text[]),
    ('Quần áo','Thắt lưng','👖','noun',ARRAY[]::text[]),
    ('Quần áo','Ba lô','🎒','noun',ARRAY[]::text[]),
    ('Quần áo','Áo mưa','🧥','noun',ARRAY[]::text[]),

    ('Vệ sinh','Rửa tay','🧼','verb',ARRAY[]::text[]),
    ('Vệ sinh','Đánh răng','🪥','verb',ARRAY[]::text[]),
    ('Vệ sinh','Tắm','🛁','verb',ARRAY['evening']),
    ('Vệ sinh','Gội đầu','🧴','verb',ARRAY[]::text[]),
    ('Vệ sinh','Lau mặt','🧻','verb',ARRAY[]::text[]),
    ('Vệ sinh','Xà phòng','🧼','noun',ARRAY[]::text[]),
    ('Vệ sinh','Dầu gội','🧴','noun',ARRAY[]::text[]),
    ('Vệ sinh','Kem đánh răng','🪥','noun',ARRAY[]::text[]),
    ('Vệ sinh','Khăn tắm','🧻','noun',ARRAY[]::text[]),
    ('Vệ sinh','Khăn giấy','🧻','noun',ARRAY[]::text[]),
    ('Vệ sinh','Bồn cầu','🚽','noun',ARRAY[]::text[]),
    ('Vệ sinh','Đi vệ sinh','🚽','verb',ARRAY[]::text[]),
    ('Vệ sinh','Tã','🩲','noun',ARRAY[]::text[]),
    ('Vệ sinh','Cắt móng','💅','verb',ARRAY[]::text[]),
    ('Vệ sinh','Cắt tóc','💇','verb',ARRAY[]::text[]),
    ('Vệ sinh','Chải tóc','💆','verb',ARRAY[]::text[]),
    ('Vệ sinh','Rửa mặt','💦','verb',ARRAY[]::text[]),
    ('Vệ sinh','Lau nhà','🧹','verb',ARRAY[]::text[]),
    ('Vệ sinh','Giặt đồ','🧺','verb',ARRAY[]::text[]),
    ('Vệ sinh','Vứt rác','🗑️','verb',ARRAY[]::text[]),

    ('Nơi chốn','Nhà','🏠','noun',ARRAY[]::text[]),
    ('Nơi chốn','Trường','🏫','noun',ARRAY[]::text[]),
    ('Nơi chốn','Lớp học','🪑','noun',ARRAY[]::text[]),
    ('Nơi chốn','Công viên','🏞️','noun',ARRAY[]::text[]),
    ('Nơi chốn','Sân chơi','🛝','noun',ARRAY[]::text[]),
    ('Nơi chốn','Siêu thị','🛒','noun',ARRAY[]::text[]),
    ('Nơi chốn','Chợ','🏪','noun',ARRAY[]::text[]),
    ('Nơi chốn','Bệnh viện','🏥','noun',ARRAY[]::text[]),
    ('Nơi chốn','Nhà thuốc','💊','noun',ARRAY[]::text[]),
    ('Nơi chốn','Nhà hàng','🍽️','noun',ARRAY[]::text[]),
    ('Nơi chốn','Quán cà phê','☕','noun',ARRAY[]::text[]),
    ('Nơi chốn','Bãi biển','🏖️','noun',ARRAY[]::text[]),
    ('Nơi chốn','Núi','⛰️','noun',ARRAY[]::text[]),
    ('Nơi chốn','Sông','🏞️','noun',ARRAY[]::text[]),
    ('Nơi chốn','Hồ','🌊','noun',ARRAY[]::text[]),
    ('Nơi chốn','Sân bay','🛫','noun',ARRAY[]::text[]),
    ('Nơi chốn','Bến xe','🚏','noun',ARRAY[]::text[]),
    ('Nơi chốn','Ga tàu','🚉','noun',ARRAY[]::text[]),
    ('Nơi chốn','Sở thú','🦁','noun',ARRAY[]::text[]),
    ('Nơi chốn','Thư viện','📚','noun',ARRAY[]::text[]),

    ('Cụm chức năng','Con muốn ăn','🍽️','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con muốn uống','🥤','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con muốn ngủ','😴','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con muốn chơi','🎮','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con muốn đi','🚶','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con đói rồi','🍚','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con khát rồi','💧','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con mệt rồi','😪','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con đau','🤕','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con yêu mẹ','❤️','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con yêu bố','💙','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Mẹ ơi','📣','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Bố ơi','📣','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Cho con xin','🤲','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con không thích','🙅','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Con thích','😍','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Đi chơi','🎡','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Về nhà','🏠','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Đi học','🎒','phrase',ARRAY[]::text[]),
    ('Cụm chức năng','Chúc ngủ ngon','🌙','phrase',ARRAY[]::text[])
  ) AS v(cat_name, label, emoji, pos, tags) ON v.cat_name = c.name
  WHERE c.child_id = p_child_id;
END;
$$;

-- Replace trigger function to call the helper
CREATE OR REPLACE FUNCTION public.seed_default_categories()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  PERFORM public.seed_categories_for_child(NEW.id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_child_created ON public.children;
CREATE TRIGGER on_child_created
AFTER INSERT ON public.children
FOR EACH ROW EXECUTE FUNCTION public.seed_default_categories();

-- Backfill existing children that don't have 18 categories yet
DO $$
DECLARE
  ch_id uuid;
BEGIN
  FOR ch_id IN
    SELECT c.id
    FROM public.children c
    LEFT JOIN public.categories cat ON cat.child_id = c.id
    GROUP BY c.id
    HAVING COUNT(cat.id) < 18
  LOOP
    DELETE FROM public.cards WHERE child_id = ch_id;
    DELETE FROM public.categories WHERE child_id = ch_id;
    PERFORM public.seed_categories_for_child(ch_id);
  END LOOP;
END $$;
